#! /usr/bin/env python

'''Run the VieSched++ container with X11 support

Typical usage: %(prog)s --host somehost

Usage Notes:
  - Any additional arguments will be sent to the container engine
  - SSH is always used in order to tunnel X11
  - Outer SSH connection authenticates user and host(s)
  - Inner SSH connection is unauthenticated and does not use networking

Requirements:
  - This host must have Python 3.X or 2.7
  - Remote host must have docker or podman installed
  - Remote host must have a VieSched++ container loaded
'''

# TODO --finals, -f  remote EOP finals path (may need to search directory)
# TODO --root, --out, --catalogs, --master or similar for setting dirs

import argparse
import subprocess
import sys

try:
    from shlex import quote
except ImportError:
    from pipes import quote

p = argparse.ArgumentParser(
    description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
)
p.add_argument(
    '--image', '-i', default='vieschedpp',
    help='run this container name (default %(default)s)'
)
p.add_argument(
    '--host', '-n', default='',
    help='SSH to this host and run container on it (default \'\' for n/a)'
)
p.add_argument(
    '--engine', '-e', default='docker,podman',
    help='list of container engine(s) to try to use (default %(default)s)'
)
p.add_argument(
    '--master', '-m', default='master',
    help='path to master files dir on container host (default %(default)s)'
)
p.add_argument(
    '--catalogs', '-c', default='catalogs',
    help='path to catalog files dir on container host (default %(default)s)'
)
p.add_argument(
    '--finals', '-f', default='',
    help='path to finals file, e.g. if not in catalogs (default \'\' for n/a)'
)
p.add_argument(
    '--mode', '-p', default='Z,ro', help=(
        'mount mode for --master, --catalogs, and --finals; options are '
        'ro (read only), rw (read and write), z (naive SELinux permissions), '
        'and Z (container-aware SELinux permissions); z or Z can be combined '
        'with ro or rw with a comma; (default is Z,ro)'
    )
)
a, extra_args = p.parse_known_args()

# set up proxy command
engine = a.engine.replace(',', ' ').split() or ['docker', 'podman']
if len(engine) == 1:
    engine = quote(engine[0])
else:
    engine = ('$(' + ''.join(
        f'(type {quote(app)}>/dev/null 2>&1&&echo {quote(app)})||'
        for app in engine[:-1]
    ) + f'echo {quote(engine[-1])})')
extra_args = ''.join(' ' + quote(arg) for arg in extra_args)
if a.master:
    x, _, m = a.master.partition(':')
    x, m = quote(x or '.'), quote(m or a.mode)
    extra_args += f' $([ -e {x} ] && echo -v {x}:/root/AUTO_DOWNLOAD_MASTER:{m} || echo warning: not found: {x}>&2)'
if a.catalogs:
    x, _, m = a.catalogs.partition(':')
    x, m = quote(x or '.'), quote(m or a.mode)
    extra_args += f' $([ -e {x} ] && echo -v {x}:/root/AUTO_DOWNLOAD_CATALOGS:{m} || echo warning: not found: {x}>&2)'
if a.finals:
    x, _, m = a.finals.partition(':')
    x, m = quote(x or '.'), quote(m or a.mode)
    extra_args += f' $([ -e {x} ] && echo -v {x}:/root/AUTO_DOWNLOAD_CATALOGS/9_FINALS.ALL_IAU2000_V2013_019.txt:{m} || echo warning: not found: {x}>&2)'
cmd = f'{engine} run --cap-add AUDIT_WRITE --rm -i{extra_args} {quote(a.image)}'
cmd = cmd + ' /usr/sbin/sshd -i'
if a.host not in '-':
    cmd = f'ssh {quote(a.host)} {quote(cmd)}'
cmd = [
    'ssh', '-Fnone', '-oUser root', f'-oProxyCommand {cmd}',
    '-oStrictHostKeyChecking no', '-oUserKnownHostsFile /dev/null',
    '-oForwardX11 yes', '-oForwardX11Trusted yes', '-oLogLevel error', '_'
]
sys.stdout.write(' '.join(map(quote, cmd)) + '\n')
exit(subprocess.Popen(cmd).wait())
